language: python
python:
- '2.7'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- cd client
- npm run test-single-run
- cd ..
notifications:
  email:
  - pmaidens@ualberta.ca
  - kchow3@ualberta.ca
  - bkhunter@ualberta.ca
  - sjpartri@ualberta.ca
  - bpeychof@ualberta.ca
  slack:
    rooms:
      secure: c18PkiGvEwnoumQOcySZsqZJt52Y4efU6sTmJFI+dyZ2QCbJ0BmdM7zSY144h44RBKOyzBTUIAnGxYo8G0WL0Uvb5lWcRY3xuDkOltNMMeheQ4M/7JniWtDo7EN6PsbHBmiUaNohOZZWMQQfMmyL05tQeSP/DastuTWwl4QSLtfGSpFjSnSSnw7hAZBP86yLALWhgMNJU+vZn127sKj8OQb0QWpXYOnSWhxPumxpDWYVZV89VIGRSudxTwQ/7iArce9RP0pd3c5xH87vTqowvG+d0z2c5s5tmNst2ExVHo9j7se7ZcfDuMZ7cU+LQcXppSYG7YXwsofdn880gLNSirmkt9pw1HTHszX8E8XgnCT6/wC58Cut2BWP2FLgzUPaUcIvc62Du0Q3i61LkaNv07J/YHcOHHyiintrOpyBepRbsz209XbV6ZAlbx/i1eIO/IExy/bT/pyt9D65uXHHess2Hf33wuhduozjf0hoe1iaf/i1of+BX1ShzbrmD2tb6sQeUiCNxF+fp7M/ZuCYwucxI8IddnDK3Elip+OfFREJXGY669QbkMypjzx10fVraqdYUIECsH24GWTAaO0UTxnTRT6nXlA2tVh461hRUD+OX2DuXGEaMRict4m4otEP7UnBU1qYDLkkvo3NAOYp8Wnt/xDjITWHTy6i3/9KPlw=
