language: python
python:
  - "2.7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - cd client
  - ENV=travis npm test
  - cd ../server
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests
