language: python
python:
  - "2.7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
script:
  - cd client
  - npm run test-single-run
  - cd ../server
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests
