# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingAPI', '0002_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=b'', max_length=2000),
        ),
    ]
