# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingAPI', '0003_auto_20160221_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BloggingAPI.Post'),
            preserve_default=False,
        ),
    ]
