# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingAPI', '0003_auto_20160306_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='author_id',
            field=models.UUIDField(default=None),
        ),
    ]
