# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingAPI', '0004_friend_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pendingFriends',
            field=models.ManyToManyField(blank=True, related_name='friendReq', to='BloggingAPI.Friend'),
        ),
    ]
