# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingAPI', '0005_auto_20160404_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, default=b'', max_length=2000, null=True),
        ),
    ]
